---
name: Publish Package to npmjs

on:
  release:
    types: [published]
  push:
    branches:
      - feat/nlap-2596/video-player-instrumentation

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'
          always-auth: true
          scope: '@nolemonnomelon'
      - run: |
            # npm confit set //npm.pkg.github.com/:_authToken ${NODE_AUTH_TOKEN}
            # npm login --registry=https://npm.pkg.github.com
            echo "//npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}
            @nolemonnomelon:registry=https://npm.pkg.github.com/" > ~/.npmrc
            yarn && yarn publish --access=restricted
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_NN_VIDEO_PAT }}
